### ISSUE TITLE
HDRP issue

### ISSUE THREAD

**Issue by AlKitChung** [clarte53/GaussianSplattingVRViewerUnity#11]
Hi,

Thank you for creating and sharing the project! I attempted to implement the plugin into an HDRP project, but the Gaussian splatting  does not appear in the display. Does the project not support HDRP, and if that's the case, what can I do to make it work? Would the shaders need to be rewritten to function with HDRP?

**Comment by Peamon** [comment]
Actually i use Blit on Camera to draw the gaussian splatting in OnPostRender (script GaussianSplattingCameraBlit). This method is only compatible with standard pipeline. You have to change that for HDRP and probably rewrite the associated shader.

There is also something to change in GaussianSplatting.cs script because i use OnPreRenderCallback too.

**Comment by AlKitChung** [comment]
Thank you!!
