### ISSUE TITLE
Multiple 3DGS

### ISSUE THREAD

**Issue by sjdingcn** [clarte53/GaussianSplattingVRViewerUnity#12]
Hi, 
Thank you for the great work.
May I ask how can I import multiple 3DGS into this viewer?
I want to show the result after doing segmentation on a 3DGS, so it is gonna be multiple 3DGS.

Thanks.

**Comment by Peamon** [comment]
Hi, We are working on it currently, and we are also working on depth support and transparency to have a fully integrable plugins for rendering in unity. It will be available before the 10 march because we will use those functionalities for a demo.

You can check the solution provided by [changruizhu96](https://github.com/changruizhu96) in issue https://github.com/clarte53/GaussianSplattingVRViewerUnity/issues/2 even if it's not the best optimized way to do that.

**Comment by sjdingcn** [comment]
Thank you so much. I am looking forward.

**Comment by Peamon** [comment]
It's done in the new version [v1.2](https://github.com/clarte53/GaussianSplattingVRViewerUnity/tree/v1.2)
