### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by JonaTh4nX** [clarte53/GaussianSplattingVRViewerUnity#30]
Hi there, 

I just downloaded the Unity project, and in the scenes, the base path pointing to the file is never correct. When I try to change it, I get a runtime error.

For example, in the "`DanceSiyu`" scene, I replace the original path: `C:/Users/g1n0st/Desktop/GaussianSplattingVRViewerUnity/Data/dance_siyu/`

with the local path corresponding to the project: `C:\Users\33601\Desktop\WIPGS\VR-GS\VR-GS\Data\dance_siyu`

Any help ? 

![error](https://github.com/user-attachments/assets/cc8ae979-31f6-49eb-9b8c-86be966decd4)

**Comment by Peamon** [comment]
I don't understand what you are talking about. there is no "DanceSiyu" scene in this project.

For your first question, have you followed this because to make the project work, you need to copy default_model.bytes before opening the unity project the first time : 
https://github.com/clarte53/GaussianSplattingVRViewerUnity/tree/master/GaussianSplattingVRViewer#starting

**Comment by JonaTh4nX** [comment]
Thanks !
