### ISSUE TITLE
Is this project alive and question on Quest 3

### ISSUE THREAD

**Issue by akutterxressential** [clarte53/GaussianSplattingVRViewerUnity#31]
Hi guys,

sorry to use an issue for that (I am not to familiar with github), but is this project still alive and under development? I am asking because we have a customer request and I wouldn`t want to use a project that is not active anymore.

And: is this tool working for GSplats on Quest 3? Or only PC VR?

Thanks and regards  @yoyoooooooo  @terziman  @Peamon

**Comment by Peamon** [comment]
The project is still working but it will not change a lot from now. It's a sample project to show how the original gaussian renderer can be integrated in Unity.

This tool will never work on Quest3 because we use CUDA to render splats. if you need this functionality you shouldn't start from here ;-).

Best regards.
